#define IDC_MYICON                      2
#define IDD_SYSTRAYDEMO_DIALOG          102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_APPTOOLTIP                  104
#define IDM_EXIT                        105
#define IDI_SYSTRAYDEMO                 107
#define IDI_SMALL                       108
#define IDC_SYSTRAYDEMO                 109
#define IDR_MAINFRAME                   128
#define ID_S_                           32771
#define ID_S_EXIT                       32772
#define ID_SYSTRAYMENU_                 32773
#define ID_SYSTRAYMENU_ENABLE           32774
#define ID_SYSTRAYMENU_DISABLE          32775
#define ID_SYSTRAYMENU_TEST1            32776
#define ID_SYSTRAYMENU_TEST2            32777
#define IDM_DISABLE                     32778
#define IDM_ENABLE                      32779
#define IDM_TEST2                       32780
#define IDM_TEST1                       32781
#define ID_SYSTRAYMENU_SEP              32782
#define IDM_SEP                         32783
#define IDC_STATIC                      -1
